# Generated by Django 6.0.6 on 2026-07-17 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('visitor_session_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='کلید نشست بازدیدکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع گفتگو')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین فعالیت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisor_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی مشاور',
                'verbose_name_plural': 'گفتگوهای مشاور',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار هوش مصنوعی')], max_length=10, verbose_name='نقش ارسال\u200cکننده')),
                ('content', models.TextField(verbose_name='محتوای پیام')),
                ('detected_tone', models.CharField(blank=True, max_length=50, null=True, verbose_name='لحن شناسایی\u200cشده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ارسال')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisor.conversation', verbose_name='گفتگو')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
