# Generated by Django 6.0.7 on 2026-07-27 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_address_options_address_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(default=datetime.datetime(2026, 7, 27, 7, 38, 18, 532412, tzinfo=datetime.timezone.utc), max_length=15),
            preserve_default=False,
        ),
    ]
