# Generated by Django 6.0.6 on 2026-07-13 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRE', 'در حال آماده\u200cسازی و بسته\u200cبندی'), ('SHI', 'تحویل شرکت حمل و نقل شده'), ('DEL', 'تحویل مشتری شده'), ('CAN', 'لغو شده')], default='PRE', max_length=3, verbose_name='وضعیت ارسال')),
                ('carrier', models.CharField(choices=[('POST', 'شرکت ملی پست'), ('TIPX', 'تیپاکس'), ('PEYK', 'پیک اختصاصی')], default='POST', max_length=4, verbose_name='شرکت حمل و نقل')),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد رهگیری مرسوله')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد مرسوله')),
                ('shipped_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ خروج از انبار')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تحویل به مشتری')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shipment', to='orders.order', verbose_name='سفارش مربوطه')),
            ],
            options={
                'verbose_name': 'مرسوله',
                'verbose_name_plural': 'مرسولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
